# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 13:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='eng_title',
            field=models.TextField(default='noname'),
            preserve_default=False,
        ),
    ]
